# tmux plugins via tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"

# make colors work in wezterm
set-option -sa terminal-overrides ",xterm*:Tc"

# Default prefix C-b collides with vim page-up and coc#float#scroll. Move to C-a.
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
