"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
disabled = false

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '

# [custom.jj]
# starship-jj is configured in starship-jj.toml
